FROM wordpress:latest

# install wp-cli
RUN curl -L -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

# copy files
COPY init.php /var/www/html/init.php

# change permissions
RUN chmod +x /var/www/html/init.php
